name: Deploy to BunnyCDN
 
on:
  workflow_dispatch:
 
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to BunnyCDN
        uses: ayeressian/bunnycdn-storage-deploy@v2
        with:
          source: ""
          destination: ""
          storageZoneName: "${{ secrets.STORAGE_NAME }}"
          storagePassword: "${{ secrets.STORAGE_PASSWORD }}"
          upload: "true"
          remove: "false"
          purgePullZone: "false"
