name: Upload to bunny
 
on:
  workflow_dispatch:
 
jobs:
  upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22.3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to BunnyCDN
        uses: ayeressian/bunnycdn-storage-deploy@v2.2.4
        with:
          source: ""
          destination: ""
          storageZoneName: "${{ secrets.STORAGE_NAME }}"
          storagePassword: "${{ secrets.STORAGE_PASSWORD }}"
          upload: "true"
          remove: "false"
          purgePullZone: "false"

          
